"""Create Data Transfer Objects (DTO).

This submodule contains all Create DTOs for each Database entity (table).
Create DTOs are used a bridge between User and Database (ORM objects)

"""

from datetime import date

from pydantic import BaseModel


class CreateGenderDTO(BaseModel):
    """Creation Data Transfer Object (DTO) for `Gender` entity.

    Defines the required data and validation for creating a new gender
    lookup record in the database. This schema intentionally omits the
    primary key 'id', as it will be generated by the database.

    :param gender_abb:
        Gender standarized abbreviation `('M', 'F')`

    :param gender_name:
        Gender name or description `(MALE, FEMALE)`
    """

    gender_abb: str
    gender_name: str


class CreateDocumentTypeDTO(BaseModel):
    """Creation Data Transfer Object (DTO) for `DocumentType` entity.

    Defines the required data and validation for creating a new document type
    lookup record in the database. This schema intentionally omits the
    primary key 'id', as it will be generated by the database.

    :param document_type_abb:
        `DocumentType` standarized abbreviation `(RC, TI, CC)`

    :param document_type_name:
        `DocumentType` name or description `(REGISTRO CIVIL, TARJETA DE IDENTIDAD,
        CEDULA DE CIUDADANIA)`
    """

    document_type_abb: str
    document_type_name: str


class CreateProcedureDTO(BaseModel):
    """Creation Data Transfer Object (DTO) for `Procedure` entity.

    Defines the required data and validation for creating a new procedure
    lookup record in the database. This schema intentionally omits the
    primary key 'id', as it will be generated by the database.

    :param cups:
        `Procedure` unique code (e.g. `881302`)

    :param procedure_name:
        `Procedure` name or description (e.g. `ECOGRAFIA DE ABDOMEN TOTAL`)

    :param procedure_price:
        `Procedure` price ($`300.000` COP)
    """

    cups: str
    procedure_name: str
    procedure_price: int


class CreatePhysicianDTO(BaseModel):
    """Creation Data Transfer Object (DTO) for `Physician` entity.

    Defines the required data and validation for creating a new physician
    lookup record in the database. This schema intentionally omits the
    primary key 'id', as it will be generated by the database.

    :param physician_rm:
        `Physician` medical license identifier (e.g. `12345`)

    :param physician_name:
        `Physician` full name (e.g. `PHYSICIAN TEST A`)

    """

    physician_rm: str
    physician_name: str


class CreateReferralDTO(BaseModel):
    """Creation Data Transfer Object (DTO) for `Referral` entity.

    Defines the required data and validation for creating a new referral
    lookup record in the database. This schema intentionally omits the
    primary key 'id', as it will be generated by the database.

    :param referral_rm:
        `Referral` medical license identifier (e.g. `54321`)

    :param referral_name:
        `Referral` name (e.g. `TEST REFERRAL A`)

    """

    referral_rm: str
    referral_name: str


class CreatePatientDTO(BaseModel):
    """Creation Data Transfer Object (DTO) for the Patient entity.

    Defines the required data and validation for registering a new patient.
    The primary key 'id' is omitted as it will be generated by the database.

    :param id_document_type:
        Foreing key referencing `id_document_type` in `DocumentType` table.

    :param identification:
        Patient legal identification number

    :param id_gender:
        Foreing key referencing `id_gender` in `Gender` table.

    :param date_of_birth:
        Patient date of birth as `datetime.date` object

    :param name:
        The full legal name of the patient.
    """

    id_document_type: int
    identification: str
    id_gender: int
    date_of_birth: date
    name: str


class CreateStudyDTO(BaseModel):
    """Creation Data Transfer Object (DTO) for the Study entity.

    Defines the required data and validation for registering a new study.
    The primary key 'id' is omitted as it will be generated by the database.

    :param id_patient:
        Foreing key referencing `id_patient` in `Patient` table.

    :param study_date:
        Study date as `datetime.date` object

    :param id_procedure:
        Foreing key referencing `id_procedure` in `Procedure` table.

    :param id_physician:
        Foreing key referencing `id_physician` in `Physician` table.

    :param id_referral:
        Foreing key referencing `id_referral` in `Referral` table.

    """

    id_patient: int
    study_date: date
    id_procedure: int
    id_physician: int
    id_referral: int
